### ISSUE TITLE
CoroutineContextProvider should be interface

### ISSUE THREAD

**Issue by IRus** [Colibridev/CoroutinesUnitTests#2]
There is no advantages using open classes over interfaces, so CoroutineContextProvider should be interface which has few implementations:

```
interface CoroutineContextProvider {
    val Main: CoroutineContext
    val IO: CoroutineContext
}

class AppCoroutineContextProvider : CoroutineContextProvider {
    override val Main: CoroutineContext by lazy { UI }
    override val IO: CoroutineContext by lazy { CommonPool }
}

class TestContextProvider : CoroutineContextProvider {
    override val Main: CoroutineContext = Unconfined
    override val IO: CoroutineContext = Unconfined
}
```

Also will be good to move `TestContextProvider` in separate file.

**Comment by Colibridev** [comment]
@IRus thank you for reporting, but I don't think that I need  interface in this situation. I can't image any case when I need to create another implementation of this interface. Also `AppCoroutineContextProvider` sounds a little bit strange for me. This stopped me to create this interface. 
  
Agree that `TestContextProvider`  should be in different file, but I'm just so lazy to do it for sample project.
